name: Liz Anderson
title: lizthree Github
logo: /assets/img/liz_face.jpg
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: PST
values:
  layout: "default"


# Author Settings
author: Liz Anderson 
author-img: /assets/img/liz_face.jpg 
about-author: Hello! I'm currently taking data science courses online and tracking my progress and projects here.
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: lizthree # add your Github handle
social-linkedin: lizthree
social-email: lizanderson.ca@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here
